/// Product subcategory dimension table providing detailed classification within product categories. Acts as a bridge between high-level categories and individual products. Essential for granular product analysis and enables hierarchical navigation from category to subcategory level for detailed business insights.
table 'Product Subcategories Lookup'
	lineageTag: e66a91be-cc07-4824-8388-6d18937d8353

	column ProductSubcategoryKey
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: 5cd5ee20-ef25-453d-8a92-6a7696110671
		summarizeBy: none
		sourceColumn: ProductSubcategoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column SubcategoryName
		dataType: string
		lineageTag: 4bf4f107-19e1-4951-b6ba-3e1c080731f2
		summarizeBy: none
		sourceColumn: SubcategoryName

		annotation SummarizationSetBy = Automatic

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: 69f97d5c-c01b-4177-9b24-2b106932a1ed
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	partition 'Product Subcategories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Adventure Works\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Product Subcategories Lookup.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductSubcategoryKey", Int64.Type}, {"SubcategoryName", type text}, {"ProductCategoryKey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

