/// Returns fact table containing all product return transactions. Tracks returned items with associated reasons, quantities, and references to original sales. Essential for calculating return rates, analyzing return patterns, and understanding product quality issues or customer satisfaction concerns.
table 'Returns Data'
	lineageTag: 067abba7-5a9c-4367-8fb3-dea594309332

	column ReturnDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: e77ae2e4-ff1d-40b3-90eb-70d7f002edf3
		summarizeBy: none
		sourceColumn: ReturnDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column TerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: ed0fab57-8ce1-46df-a8dc-cec962d1d49a
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 5da29ecf-e774-491e-b53d-a89b8693f57b
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReturnQuantity
		dataType: int64
		formatString: 0
		lineageTag: 59c63780-8ce5-4738-b592-e3105730a314
		summarizeBy: sum
		sourceColumn: ReturnQuantity

		annotation SummarizationSetBy = Automatic

	partition 'Returns Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Adventure Works\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Returns Data.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ReturnDate", type date}, {"TerritoryKey", Int64.Type}, {"ProductKey", Int64.Type}, {"ReturnQuantity", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

