/// Primary sales fact table containing all sales transactions with order details. Each row represents a line item from a customer order, including quantity sold and key references to related dimensions. This is the main table for calculating revenue, profit, and sales volume metrics.
table 'Sales Data'
	lineageTag: c5874b38-d88e-4658-94a1-8c3d398b5830

	column OrderDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: ef33ce8d-8d17-4e0f-9444-266878887b33
		summarizeBy: none
		sourceColumn: OrderDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column StockDate
		dataType: dateTime
		isHidden
		formatString: Short Date
		lineageTag: 034ca60b-492b-4911-b1de-aa83dadb9dda
		summarizeBy: none
		sourceColumn: StockDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column OrderNumber
		dataType: string
		lineageTag: bb8142e8-bbb1-4a1d-a92b-cdc5b87788db
		summarizeBy: none
		sourceColumn: OrderNumber

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f28e6e0f-e0fb-4508-9128-76853dc243c2
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 451aa15d-8a60-4748-a2ef-4c103467e594
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TerritoryKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4e599af8-3946-4d7a-95b0-306f724856a8
		summarizeBy: none
		sourceColumn: TerritoryKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column OrderLineItem
		dataType: int64
		formatString: 0
		lineageTag: d6a314e1-9c95-49c3-8d36-474fbb3a2853
		summarizeBy: sum
		sourceColumn: OrderLineItem

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: b1cb9cfc-9a6b-46a3-a94f-1c53779811bd
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column QuantityType =
			
			IF(
			    'Sales Data'[OrderQuantity]=1,"Single Item","Multiple Items"
			    )
		lineageTag: 77eb0670-a807-4aaf-bc4c-6925785def42
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Sales Data' = m
		mode: import
		source =
				let
				    Source = Folder.Files("D:\Power BI\Adventure Works\AdventureWorks+Raw+Data\AdventureWorks Raw Data\Sales Data"),
				    #"Filtered Hidden Files1" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),
				    #"Invoke Custom Function1" = Table.AddColumn(#"Filtered Hidden Files1", "Transform File", each #"Transform File"([Content])),
				    #"Renamed Columns1" = Table.RenameColumns(#"Invoke Custom Function1", {"Name", "Source.Name"}),
				    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns1", {"Source.Name", "Transform File"}),
				    #"Expanded Table Column1" = Table.ExpandTableColumn(#"Removed Other Columns1", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Table Column1",{{"Source.Name", type text}, {"OrderDate", type date}, {"StockDate", type date}, {"OrderNumber", type text}, {"ProductKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"TerritoryKey", Int64.Type}, {"OrderLineItem", Int64.Type}, {"OrderQuantity", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Source.Name"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

